name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.bump-level }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - bump-level: patch
            current-version: v1.2.3
            expected: v1.2.4
          - bump-level: minor
            current-version: v1.2.3
            expected: v1.3.0
          - bump-level: major
            current-version: v1.2.3
            expected: v2.0.0
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          bump-level: ${{ matrix.bump-level }}
          current-version: ${{ matrix.current-version }}

      - name: Verify
        env:
          ACTUAL: ${{ steps.exercise.outputs.version }}
          EXPECTED: ${{ matrix.expected }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-git-tag:
    name: git tag
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          bump-level: major

      - name: Verify
        env:
          ACTUAL: ${{ steps.exercise.outputs.version }}
        run: |
          set -x
          test "${ACTUAL}" = "v1.0.0"
